name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set timeout to 30 minutes

    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Set up Xvfb for GUI applications
      - name: Set up Xvfb
        uses: GabrielBB/xvfb-action@v1

      # Step 5: Run the main application
      - name: Run the Tkinter application
        run: |
          echo "Starting the Tkinter application at $(date)"
          python main_Run.py
          echo "Application finished at $(date)"
